# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/SignZeroExtend.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/Reg.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/PC.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/Multiplexer5.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/Multiplexer32.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/InstructionMemory.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/DataMemory.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/ControlUnit.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/ALU.v
  D:/Vivado_Project/CPU/CPU.srcs/sources_1/new/SingleCPU.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_Project/CPU/CPU.cache/wt [current_project]
set_property parent.project_dir D:/Vivado_Project/CPU [current_project]
catch { write_hwdef -file SingleCPU.hwdef }
synth_design -top SingleCPU -part xc7a35tcpg236-1
write_checkpoint SingleCPU.dcp
report_utilization -file SingleCPU_utilization_synth.rpt -pb SingleCPU_utilization_synth.pb
